<?php
	$this->headMeta()->appendName('Keywords','bklgrg,grrrrrrr,oooooo');
	$this->headMeta()->appendName('Description','et blablabla');
	$this->headTitle('Page d\'accueil');
	$this->headScript()->appendFile("http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js","text/javascript");
	//$this->headLink()->appendStylesheet('/css/specifique.css','screen');
	
?>
<h1>Index</h1>

<p>Date du jour : 
<?php echo $this->formatDate('2011-08-02');?>
</p>